<?php

//Controller is generated by MVC Schema Engine

/**
 * @property CI_Loader $load
 * @property CI_Form_validation $form_validation
 * @property CI_Input $input
 * @property CI_Email $email
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property VehicleDBUtils $VehicleDBUtils
 * @property Xe $xe
 * @property Gps_markers $gps_markers
 */
class email_service extends Controller {

    function email_service() {
        parent::Controller();
        $this->load->library('email');
    }

    /**
     * @Decorated
     * @Secured(role = "GroupOperator")
     */
    public function config_user_email() {
        //currently, only support for Gmail Account
        $data = array();
        $user_profile = $this->redux_auth->profile();
        $data['user_profile'] = $user_profile;
        $this->load->view("user/user_email_config", $data);
    }

    /**
     *
     * @Secured(role = "GroupOperator")
     */
    public function save_config_user_email() {
        //currently, only support for Gmail Account
        //{"smtp_account":{"smtp_user":"tantrieuf31.database@gmail.com","smtp_pass":"Mycatisfat@31"}}
        $data = array();
        $user_profile = $this->redux_auth->profile();
        $data['user_profile'] = $user_profile;
        echo "Saved!";
    }

    /**
     * @Secured(role = "GroupOperator")
     */
    public function send_email() {
        $user_profile = $this->redux_auth->profile();
        $ext_info_json = json_decode($user_profile->ext_info);
        $smtp_user = $ext_info_json->smtp_account->smtp_user;
        $smtp_pass = $ext_info_json->smtp_account->smtp_pass;

        $config = Array(
            'protocol' => 'smtp',
            'smtp_host' => 'ssl://smtp.googlemail.com',
            'smtp_port' => '465',
            'smtp_user' => $smtp_user,
            'smtp_pass' => $smtp_pass,
            'mailtype' => 'html',
            'charset' => 'utf-8',
            'validate' => TRUE,
            'newline' => '\r\n',
            'wordwrap' => TRUE
        );
        $this->email->initialize($config);

        $this->email->clear();
        $this->email->set_newline("\r\n");
        $this->email->from('tantrieuf31.database@gmail.com', 'tantrieuf31.database');
        $this->email->to('tantrieuf31.database@gmail.com');

        $this->email->subject('Email Test');
        $this->email->message('Testing the email class.');

        if (!$this->email->send()) {
            echo "Send email failed !";
        }

        echo $this->email->print_debugger();
    }

}

?>