<?php

//Controller is generated by MVC Schema Engine

/**
 * @property CI_Loader $load
 * @property CI_Form_validation $form_validation
 * @property CI_Input $input
 * @property CI_Email $email
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property VehicleDBUtils $VehicleDBUtils
 * @property Xe $xe
 * @property Gps_markers $gps_markers
 */
class email_service extends Controller {

    function email_service() {
        parent::Controller();
        $this->load->library('email');
    }

    /**
     * @Decorated
     * @Secured(role = "GroupOperator")
     */
    public function config_user_email() {
        //currently, only support for Gmail Account
        $data = array();
        $user_profile = $this->redux_auth->profile();
        $data['user_profile'] = $user_profile;
        $this->load->view("user/user_email_config", $data);
    }

    /**
     *
     * @Secured(role = "GroupOperator")
     */
    public function save_config_user_email() {
        //currently, only support for Gmail Account
        //{"smtp_account":{"smtp_user":"tantrieuf31.database@gmail.com","smtp_pass":"Mycatisfat@31"}}
        $ext_info = new stdClass();
        $ext_info->smtp_account = new stdClass();
        $ext_info->smtp_account->smtp_user = $this->input->post("smtp_user");
        $ext_info->smtp_account->smtp_pass = $this->input->post("smtp_pass");

        $data = array();
        $update_data = array();
        $update_data['ext_info'] = json_encode($ext_info);
        $rs = $this->redux_auth->update_profile($update_data);
        if ($rs)
            echo "Saved!";
        else
            echo "Save failed!";
    }

    protected function init_email_service_from_user_profile() {
        $user_profile = $this->redux_auth->profile();
        if ($user_profile->ext_info != NULL) {
            $user_profile->ext_info = json_decode($user_profile->ext_info);
        } else {
            // if $user_profile->ext_info === NULL, we use default configs in config/email.php
            $this->load->config('email');
            $ext_info = new stdClass();
            $ext_info->smtp_account = new stdClass();
            $ext_info->smtp_account->smtp_user = $this->config->item('smtp_user');
            $ext_info->smtp_account->smtp_pass = $this->config->item('smtp_pass');
            $user_profile->ext_info = $ext_info;
        }
        $smtp_user = $user_profile->ext_info->smtp_account->smtp_user;
        $smtp_pass = $user_profile->ext_info->smtp_account->smtp_pass;
        $config = Array(
            'protocol' => 'smtp',
            'smtp_host' => 'ssl://smtp.googlemail.com',
            'smtp_port' => '465',
            'smtp_user' => $smtp_user,
            'smtp_pass' => $smtp_pass,
            'mailtype' => 'html',
            'charset' => 'utf-8',
            'validate' => TRUE,
            'newline' => '\r\n',
            'wordwrap' => TRUE
        );
        $this->email->initialize($config);
        $this->email->clear();
        $this->email->set_newline("\r\n");
        $this->email->from($smtp_user, $user_profile->username);
        return $user_profile;
    }

    /**
     * @Secured(role = "GroupOperator")
     */
    public function test_email_service() {
        $toAddresses = $this->input->post("to_addresses");

        $user_profile = $this->init_email_service_from_user_profile();
        $smtp_user = $user_profile->ext_info->smtp_account->smtp_user;        
        $this->email->to($toAddresses);
        $this->email->subject('Email Test');
        $this->email->message('Testing the email service from ' . base_url());

        $result_text = "";
        if ($this->email->send()) {
            $result_text = '<h3 style="color:blue">The Email Service of ' . $smtp_user . '  is working OK!</h3>';
        } else {
            $result_text = '<h3 style="color:red">The Email Service of ' . $smtp_user . ' is NOT working!';
            $result_text .= "<br> Please check the email and password again! </h3>";
        }
        $result_text .= $this->email->print_debugger();
        echo $result_text;
    }

    /**
     * @Secured(role = "GroupOperator")
     */
    public function send_email() {        
        $toAddresses =  $this->input->post("to_addresses");
        $subject     =  $this->input->post("email_subject");
        $message     =  $this->input->post("email_message");

        $user_profile = $this->init_email_service_from_user_profile();
        $this->email->to($toAddresses);
        $this->email->subject($subject);
        $this->email->message($message);

        $result_text = "";
        if ($this->email->send()) {
            $result_text = '<b style="color:blue">The email is sent to the addresses"' . $toAddresses . '" OK!</b>';
        } else {
            $result_text = '<b style="color:red">The email is NOT sent to the addresses"' . $toAddresses . '"!';
            $result_text .= "<br>Something wrong happened, please check the email service configurations again! </b>";
            ApplicationHook::logError($this->email->print_debugger());
        }        
        echo $result_text;
    }

}

?>