<?php

//Controller is generated by MVC Schema Engine

/**
 * @property CI_Loader $load
 * @property CI_Form_validation $form_validation
 * @property CI_Input $input
 * @property CI_Email $email
 * @property CI_DB_active_record $db 
 */
class object_service extends Controller {

    function object_service() {
        parent::Controller();
        $this->load->library('curl');
    }

    function index() {
        phpinfo();
    }

    /**
     * 
     */
    public function export_data() {
        $data = array();
        $o = new stdClass();
        $o->name = "Trieu";
        $o->age = 25;
        echo json_encode($o);
        // $this->load->view("user/user_email_config", $data);
    }

    /**
     * 
     */
    public function import_data() {
        $url1 = 'http://tantrieuf31.summerhost.info/job-database/index.php/services/object_service/export_data';
        $url2 = 'http://drd-vn-database.com/index.php/services/object_service/export_data';
        $out = '';

        $out = $this->curl->loadHtml(($url2));

        echo $out;
    }

    public function simple_get() {
        $responce = $this->curl->simple_get('curl_test/get_message');

        echo '<h1>Simple Get</h1>';
        echo '<p>--------------------------------------------------------------------------</p>';

        if ($responce) {

            echo $responce;


            echo '<br/><p>--------------------------------------------------------------------------</p>';
            echo '<h3>Debug</h3>';
            echo '<pre>';
            print_r($this->curl->info);
            echo '</pre>';
        } else {
            echo '<strong>cURL Error</strong>: ' . $this->curl->error_string;
        }
    }

    function simple_post() {
        $responce = $this->curl->simple_post('curl_test/message', array('message' => 'Sup buddy'));

        echo '<h1>Simple Post</h1>';
        echo '<p>--------------------------------------------------------------------------</p>';

        if ($responce) {

            echo $responce;


            echo '<br/><p>--------------------------------------------------------------------------</p>';
            echo '<h3>Debug</h3>';
            echo '<pre>';
            print_r($this->curl->info);
            echo '</pre>';
        } else {
            echo '<strong>cURL Error</strong>: ' . $this->curl->error_string;
        }
    }

    function message() {
        echo "<h2>Posted Message</h2>";
        echo $_POST['message'];
    }

    function get_message() {
        echo "<h2>Get got!</h2>";
    }

    function advance() {
        $this->curl->create('curl_test/cookies')
                ->set_cookies(array('message' => 'Im advanced :-p'));

        $responce = $this->curl->execute();

        echo '<h1>Advanced</h1>';
        echo '<p>--------------------------------------------------------------------------</p>';

        if ($responce) {

            echo $responce;

            echo '<br/><p>--------------------------------------------------------------------------</p>';
            echo '<h3>Debug</h3>';
            echo '<pre>';
            print_r($this->curl->info);
            echo '</pre>';
        } else {
            echo '<strong>cURL Error</strong>: ' . $this->curl->error_string;
        }
    }

    function cookies() {
        echo "<h2>Cookies</h2>";
        print_r($_COOKIE);
    }

}

?>